In [14]:
#Program to random colldie particle together
import numpy as np

# Function for collision A+B=2C
def A(matrix):
    if matrix[0, 0] == 0 or matrix[1, 0] == 0:
        return matrix, "Collision A+B is not possible - Cannot perform when A=0 or B=0"
    else:
        matrix[0, 0] -= 1
        matrix[1, 0] -= 1
        matrix[2, 0] += 2
        return matrix, "Collision A=B=2C"

# Function for collision A+C=2B
def B(matrix):
    if matrix[0, 0] == 0 or matrix[2, 0] == 0:
        return matrix, "Collision A+C=2B is not possible- Cannot perform when A=0 or C=0"
    else:
        matrix[0, 0] -= 1
        matrix[1, 0] += 2
        matrix[2, 0] -= 1
        return matrix, "collision A+C=2B."

# Function for collision B+C=2A
def C(matrix):
    if matrix[1, 0] == 0 or matrix[2, 0] == 0:
        return matrix, "Collsiosn B+C=2A is not possible - Cannot perform when B=0 or C=0"
    else:
        matrix[0, 0] += 2
        matrix[1, 0] -= 1
        matrix[2, 0] -= 1
        return matrix, "Collision B+C=2A"

collis = [A, B, C]
num_iter = 10

print("Enter the starting values for the matrix (3 comma-separated integers):")
start_val = list(map(int, input().split(',')))
matrix = np.array(start_val).reshape(3, 1)

for i in range(num_iter):
    # Check for finial case
    if np.sum(matrix == 0) >= 2:
        print("Finial case achieved.")
        break
    
    # Each collision has equal probability
    chosen_collis = np.random.choice(collis)
    matrix, collis_des = chosen_collis(matrix)
    print(f"Iteration {i+1}: {collis_des}")
    print("Matrix after action:")
    print(matrix)
    print()

Enter the starting values for the matrix (3 comma-separated integers):
2,2,2
Iteration 1: Collision B+C=2A
Matrix after action:
[[4]
 [1]
 [1]]

Iteration 2: Collision A=B=2C
Matrix after action:
[[3]
 [0]
 [3]]

Iteration 3: collision A+C=2B.
Matrix after action:
[[2]
 [2]
 [2]]

Iteration 4: Collision B+C=2A
Matrix after action:
[[4]
 [1]
 [1]]

Iteration 5: Collision B+C=2A
Matrix after action:
[[6]
 [0]
 [0]]

Finial case achieved.


In [13]:
#Program to inspect every collision possible 
import numpy as np
from itertools import product

# Function for collision A+B=2C
def A(matrix):
    if matrix[0, 0] == 0 or matrix[1, 0] == 0:
        return False, matrix, "Collision A+B is not possible - Cannot perform when A=0 or B=0"
    else:
        matrix[0, 0] -= 1
        matrix[1, 0] -= 1
        matrix[2, 0] += 2
        return True, matrix, "Collision A+B=2C"

#Function for collision A+C=2B
def B(matrix):
    if matrix[0, 0] == 0 or matrix[2, 0] == 0:
        return False, matrix, "Collision A+C=2B is not possible- Cannot perform when A=0 or C=0"
    else:
        matrix[0, 0] -= 1
        matrix[1, 0] += 2
        matrix[2, 0] -= 1
        return True, matrix, "collision A+C=2B."

#  Function for collision B+C=2A
def C(matrix):
    if matrix[1, 0] == 0 or matrix[2, 0] == 0:
        return False, matrix, "Collsiosn B+C=2A is not possible - Cannot perform when B=0 or C=0"
    else:
        matrix[0, 0] += 2
        matrix[1, 0] -= 1
        matrix[2, 0] -= 1
        return True, matrix, "Collision B+C=2A"

# all possible collisions, length 2
collis_combo = list(product(['A', 'B', 'C'], repeat=3))

num_iter = 10

# Ask user for starting matrix
print("Enter the starting values for the matrix (3 comma-separated integers):")
start_val = list(map(int, input().split(',')))
initial_matrix = np.array(start_val).reshape(3, 1)

for combination in collis_combo:
    matrix = initial_matrix.copy()
    print(f"Initial matrix: {matrix.flatten()}")
    print(f"Applying actions: {' -> '.join(combination)}")
    for collis_name in combination:
        if collis_name == 'A':
            can_apply, matrix, collis_des = A(matrix)
        elif collis_name == 'B':
            can_apply, matrix, collis_des = B(matrix)
        elif collis_name == 'C':
            can_apply, matrix, collis_des = C(matrix)
        if not can_apply:
            print(f"Invalid action sequence. {collis_des}")
            break
        print(collis_des)
        print("Matrix after action:")
        print(matrix)
        print()
    print()

Enter the starting values for the matrix (3 comma-separated integers):
1,1,1
Initial matrix: [1 1 1]
Applying actions: A -> A -> A
Collision A+B=2C
Matrix after action:
[[0]
 [0]
 [3]]

Invalid action sequence. Collision A+B is not possible - Cannot perform when A=0 or B=0

Initial matrix: [1 1 1]
Applying actions: A -> A -> B
Collision A+B=2C
Matrix after action:
[[0]
 [0]
 [3]]

Invalid action sequence. Collision A+B is not possible - Cannot perform when A=0 or B=0

Initial matrix: [1 1 1]
Applying actions: A -> A -> C
Collision A+B=2C
Matrix after action:
[[0]
 [0]
 [3]]

Invalid action sequence. Collision A+B is not possible - Cannot perform when A=0 or B=0

Initial matrix: [1 1 1]
Applying actions: A -> B -> A
Collision A+B=2C
Matrix after action:
[[0]
 [0]
 [3]]

Invalid action sequence. Collision A+C=2B is not possible- Cannot perform when A=0 or C=0

Initial matrix: [1 1 1]
Applying actions: A -> B -> B
Collision A+B=2C
Matrix after action:
[[0]
 [0]
 [3]]

Invalid action seque

In [17]:
#Program to inspect every collision possible for extension case 
import numpy as np
from itertools import product

# Function for collision A+B=C
def A(matrix):
    if matrix[0, 0] == 0 or matrix[1, 0] == 0:
        return False, matrix, "Collision A+B is not possible - Cannot perform when A=0 or B=0"
    else:
        matrix[0, 0] -= 1
        matrix[1, 0] -= 1
        matrix[2, 0] += 1
        return True, matrix, "Collision A+B=C"

#Function for collision A+C=B
def B(matrix):
    if matrix[0, 0] == 0 or matrix[2, 0] == 0:
        return False, matrix, "Collision A+C=B is not possible- Cannot perform when A=0 or C=0"
    else:
        matrix[0, 0] -= 1
        matrix[1, 0] += 1
        matrix[2, 0] -= 1
        return True, matrix, "collision A+C=B."

#  Function for collision B+C=A
def C(matrix):
    if matrix[1, 0] == 0 or matrix[2, 0] == 0:
        return False, matrix, "Collsiosn B+C=A is not possible - Cannot perform when B=0 or C=0"
    else:
        matrix[0, 0] += 1
        matrix[1, 0] -= 1
        matrix[2, 0] -= 1
        return True, matrix, "Collision B+C=A"

# all possible collisions, length can be changed
collis_combo = list(product(['A', 'B', 'C'], repeat=8))

num_iter = 10

# Ask user for starting matrix
print("Enter the starting values for the matrix (3 comma-separated integers):")
start_val = list(map(int, input().split(',')))
initial_matrix = np.array(start_val).reshape(3, 1)

for combination in collis_combo:
    matrix = initial_matrix.copy()
    print(f"Initial matrix: {matrix.flatten()}")
    print(f"Applying actions: {' -> '.join(combination)}")
    for collis_name in combination:
        if collis_name == 'A':
            can_apply, matrix, collis_des = A(matrix)
        elif action_name == 'B':
            can_apply, matrix, collis_des = B(matrix)
        elif action_name == 'C':
            can_apply, matrix, collis_des = C(matrix)
        if not can_apply:
            print(f"Invalid action sequence. {collis_des}")
            break
        print(collis_des)
        print("Matrix after action:")
        print(matrix)
        print()
    print()

Enter the starting values for the matrix (3 comma-separated integers):
2,2,2
Initial matrix: [2 2 2]
Applying actions: A -> A -> A -> A -> A -> A -> A -> A
Collision A+B=C
Matrix after action:
[[1]
 [1]
 [3]]

Collision A+B=C
Matrix after action:
[[0]
 [0]
 [4]]

Invalid action sequence. Collision A+B is not possible - Cannot perform when A=0 or B=0

Initial matrix: [2 2 2]
Applying actions: A -> A -> A -> A -> A -> A -> A -> B
Collision A+B=C
Matrix after action:
[[1]
 [1]
 [3]]

Collision A+B=C
Matrix after action:
[[0]
 [0]
 [4]]

Invalid action sequence. Collision A+B is not possible - Cannot perform when A=0 or B=0

Initial matrix: [2 2 2]
Applying actions: A -> A -> A -> A -> A -> A -> A -> C
Collision A+B=C
Matrix after action:
[[1]
 [1]
 [3]]

Collision A+B=C
Matrix after action:
[[0]
 [0]
 [4]]

Invalid action sequence. Collision A+B is not possible - Cannot perform when A=0 or B=0

Initial matrix: [2 2 2]
Applying actions: A -> A -> A -> A -> A -> A -> B -> A
Collision A+B=C
